### ISSUE TITLE
Errors at runtime

### ISSUE THREAD

**Issue by Blackaddder** [alextrevisan/LPCAnimatedSprite2D#1]
Getting the following errors when running my project:
```
scene/main/node.h:329 - Condition "!data.tree" is true. Returning: nullptr
res://addons/LPCAnimatedSprite/LPCAnimatedSprite2D.gd:175 - Invalid get index 'edited_scene_root' (on base: 'null instance').
```

Most of the time animations are not being loaded at all in runtime. Everything works fine on editor. 

Not sure if the error is related to the issue of animations not being loaded, as they're randomly load despite the error.

EDIT: looks like the issue is in the function:
```
func _enter_tree():
	if Engine.is_editor_hint():
		LoadAnimations()
```
What it does is making animations load only in editor? after removing the if everything work as expected both in editor and in game.

**Comment by alextrevisan** [comment]
Can you please create a simple project with this error?
