### ISSUE TITLE
Can't turn off animation looping

### ISSUE THREAD

**Issue by hades200082** [alextrevisan/LPCAnimatedSprite2D#2]
Some of the animations don't need to loop. SLASH for example. 

If I turn off looping on that animation the plugin just turns it back on again.

**Comment by alextrevisan** [comment]
Ok, I'll look into that!

**Comment by alextrevisan** [comment]
Update to make the default animation for other than walk to not loop. Se if it helps you!

**Comment by hades200082** [comment]
Thanks for the quick response. That seems to have fixed the looping.
