### ISSUE TITLE
Add hair sprite for example to my human character

### ISSUE THREAD

**Issue by Fvrias** [alextrevisan/LPCAnimatedSprite2D#24]
HI Alex, I'm triying to replicate your guide video from here, but I don't know how to just download the things like hair, weapons separately, can you help me please?

Thanks in advance!

**Comment by Fvrias** [comment]
Other question too, i have an character with a spear and shield, and after import that .png to godot most of the actions animations dosnt show the weapon and shield :(

**Comment by Fvrias** [comment]
Another question, why most of the weapons dosnt make the slash or attack animation showing it? its like im hitting with the hand lol

**Comment by alextrevisan** [comment]
Hi! all the spritesheets are here: https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/tree/master/spritesheets

**Comment by Fvrias** [comment]
> Hi! all the spritesheets are here: https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/tree/master/spritesheets

Thanks Alex that really great!!! Can you tell me please how to add long sword slash.png for example to my character? i did like in your video but nothing happens

**Comment by alextrevisan** [comment]
There are a new version on the way (not released yet) that suports oversized weapons, you can download directly from github repository: https://codeload.github.com/alextrevisan/LPCAnimatedSprite2D/zip/refs/heads/main

In this version there are a simple example project that you can see this oversized weapons working

**Comment by Fvrias** [comment]
thanks!!!! thats awesome!!!!! considering im really noob in Godot terms, and im in Godot 4, i tried like 24 hours to make a code for walk but cant get to attack propperly... can you please, write a simple code for the control of the characterbody2d for get the player moving to the 4 sides, up, down, right, left, and attack in the direction im looking while i press space? i will appreciate so much if you add a reference to add the longsword.png on the code too, so then i and more ppl will learn how to add that oversized items into the game :)   


Thanks in advance my friend!!!!

**Comment by alextrevisan** [comment]
The problem with the attack is that you are using the current direction you are pressing. If you save that into a variable, then use it like this (not actual code, just the idea)

```
var lastDirection
if direction.x != 0:
    lastDirection = RIGHT if direction.x > 0 else LEFT

if is_attacking:
    if lastDirection == LEFT:
        animation = LPCAnimatedSprite2D.LPCAnimation.SLASH_LEFT
   elif lastDirection == RIGHT .........
```


this is the idea, if you keep the last direction you can play any action with that direction

**Comment by Fvrias** [comment]
Thanks really Alex! 

Tomorrow I will test it Hahaha
Yerterday I was playing around with your addon and the spritesheet master u told me and I found 2 things:

Cant get long sword slash animation down working,
If I add all that spritesheet folder my file system and scene never loads :(

Maybe im doing something wrong hehe


Cheers mate!

**Comment by alextrevisan** [comment]
Can you share your project? maybe I can help more

**Comment by Fvrias** [comment]
Thanks Alex!!

I'm on Masmorra discord, you mean this one?

**Comment by alextrevisan** [comment]
Yes, send me a message (Masmorra)
