### ISSUE TITLE
[Request] Support for AnimatedSprite3D

### ISSUE THREAD

**Issue by Pyblo** [alextrevisan/LPCAnimatedSprite2D#30]
It would be great if this was universal for AnimatedSprite2D & AnimatedSprite3D.  

In current stat it can be modified with little amount of work to be compatible with Sprite3D, but you also need to extend it to have proper settings for Texture Filter + billboard type. There is also a lot of duplicated classes, where it would be great to refactor the code so that common classes are used for both cases and each of 2D and 3D node types would have minimal amount of duplicated code.

**Comment by alextrevisan** [comment]
Hi @Pyblo It's not so simple because the root node is a Node2D, and for it to work correctly we will need a Node3D. so I need to do a rework to minimize code repetition. But it's a good feature. I'll look into it.

**Comment by Pyblo** [comment]
I managed to create a universal 2D/3D script. Will provide a pull request with my suggestion tomorrow or during the weekend.

**Comment by alextrevisan** [comment]
@Pyblo Everything working allright? I'll close  this issue since it's resolved.
