### ISSUE TITLE
Why did `LPCAnimatedSprite2D` go from Node2D to Node ?

### ISSUE THREAD

**Issue by rafidini** [alextrevisan/LPCAnimatedSprite2D#36]
**I'm submitting a ...**
  -  bug report
  -  ~feature request~
  - [~support request => Please do not submit support request here, see note at the top of this template.~

---
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

---
**What is the current behavior?**
In v4.2.2.1 `addons/LPCAnimatedSprite/LPCAnimatedSprite2D.gd` is a Node2D but it became a Node in v4.2.2.2.

---
**What is the expected behavior?**
I wanted to move the `position` (properties of a `Node2D`) of the parent node `CharacterBody2D` but it could not, while in v4.2.2.1 I can.

---
**What is the motivation / use case for changing the behavior?**
I wanna know if it is a normal behavior or not ? And why the change ?

---
**Please tell us about your environment:**
  - Version: v4.2.2.{1,2}
  - Godot 4.2.1.stable.official.b09f793f5

---
**Other information**
I think it's linked to #30.

**Comment by Loufe** [comment]
It's linked to #33. I think the solution here is to undo the change but offer a dynamic conversion between them on load. I haven't tested the new version yet but I think I'll experience the same thing.

**Comment by Loufe** [comment]
@alextrevisan maybe we can use inheritance to create a Node2D derivative of the main node for 2D and a Node of main for 3D?

**Comment by rafidini** [comment]
> @alextrevisan maybe we can use inheritance to create a Node2D derivative of the main node for 2D and a Node of main for 3D?

Maybe this :
1. `LPCAnimatedSprite2D` extends `Node2D`
2. `LPCAnimatedSprite3D` extends `Node3D`

**Comment by Loufe** [comment]
I'm working on PR right now, but this is not obvious to pick apart.
