### ISSUE TITLE
Allow user to change FPS/speed index after importing sprites

### ISSUE THREAD

**Issue by hades200082** [alextrevisan/LPCAnimatedSprite2D#4]
Similar to #2 the plugin recreates all animations on every save resulting in overwriting the FPS or speed index settings the dev has chosen.

It might be better to only regenerate the animations if the underlying sprite sheet is changed.

**Comment by alextrevisan** [comment]
The recreation is important for some reasons like: reorder, reassign spritesheets, renames. If I @extern the property to the user to change the FPS will satistfy your need?

**Comment by hades200082** [comment]
Possibly. My use case is that different characters have different movement/attack speeds and I want to make the corresponding animation look faster to match.

If the FPS can be exported on a per-animation basis then this would work, but if it's one FPS for all of the animations on the sprite sheet then it won't work for my case I think.

**Comment by alextrevisan** [comment]
Maybe then I can export a boolean property to disable recreation

**Comment by alextrevisan** [comment]
Done!
